FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/src
COPY serve /app/serve
COPY model_registry /app/model_registry

EXPOSE 8000
# CMD ["uvicorn", "serve.app:app", "--host", "0.0.0.0", "--port", "8000"]

# replace the last line (CMD) with:
CMD ["sh", "-c", "uvicorn serve.app:app --host 0.0.0.0 --port ${PORT:-8000}"]