name: MLOps | train→register→approve

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'requirements.txt'
      - '.github/workflows/mlops-train-register-approve.yml'
  workflow_dispatch: {}

permissions:
  contents: write   # needed to push changes back

concurrency:
  group: mlops-train-register-approve
  cancel-in-progress: true

jobs:
  build-train-register-approve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Train
        run: python src/train.py

      - name: Register model
        run: python src/register.py

      - name: Approve latest to Production
        run: python src/approve.py --version latest

      - name: Commit model_registry changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A model_registry
          if ! git diff --cached --quiet; then
            git commit -m "ci: auto-register model ($(date -u +%Y-%m-%dT%H:%M:%SZ))"
            git push
          else
            echo "No changes to commit."
          fi

      - name: (Optional) Trigger Render deploy hook
        if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
        run: |
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK"